compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-4.1.1.cjs
